### ISSUE TITLE
Image doesn't process if it isn't "touched" on the crop screen

### ISSUE THREAD

**Issue by corecarewellness** [JrSchild/jr-crop#16] opened 2015-04-21 08:03 UTC
Hi there!

First of all, I'm a huge fan of this module, it's been working really well for my app.  

However, there is one issue (seems to only happen on iOS)...

1. I select an image to crop.
2. I'm taken to the crop screen with the image properly displayed.
3. I don't touch the image or move it in any way, I simply click "Crop" right away.
4. It doesn't seem like anything gets returned from the canvas.toDataURL() method.

Any thoughts?

**Comment by yannlombard** [comment] 2015-05-03 14:25
+1

**Comment by JrSchild** [comment] 2015-05-24 08:00
This bug doesn't seem to appear with me.
- Does this happen on the device only or also in the simulator?
- What OS version are you using?
- Could you create a demo that reproduces this in simulator?

**Comment by JrSchild** [comment] 2015-11-12 12:48
Closing since I can't replicate this anymore. Assuming it's fixed, if not, please open again.

**Closed by JrSchild** 2015-11-12 12:48 UTC
